INSERT INTO stg.stg_fifa_wc
SELECT DISTINCT
    TRIM(tournament_name),
    TRIM(stage_name),
    TRIM(group_name),
    TRIM(group_stage)::FLOAT::SMALLINT,
    TRIM(knockout_stage)::FLOAT::SMALLINT,
    TRIM(match_date)::DATE,
    TRIM(match_time)::TIME,
    TRIM(stadium_name),
    TRIM(city_name),
    TRIM(country_name),
    TRIM(team_name),
    TRIM(team_code),
    TRIM(opponent_name),
    TRIM(opponent_code),
    TRIM(home_team)::FLOAT::SMALLINT,
    TRIM(away_team)::FLOAT::SMALLINT,
    TRIM(goals_for)::FLOAT::SMALLINT,
    TRIM(goals_against)::FLOAT::SMALLINT,
    TRIM(extra_time)::FLOAT::SMALLINT,
    TRIM(penalty_shootout)::FLOAT::SMALLINT,
    TRIM(penalties_for)::FLOAT::SMALLINT,
    TRIM(penalties_against)::FLOAT::SMALLINT,
    TRIM(result),
    TRIM(is_host)::FLOAT::SMALLINT,
    TRIM(yellow_cards)::FLOAT::SMALLINT,
    TRIM(red_cards)::FLOAT::SMALLINT,
    NULLIF(TRIM(possession), '')::NUMERIC(5,2),
    NULLIF(TRIM(shots), '')::FLOAT::SMALLINT,
    NULLIF(TRIM(shots_on_target), '')::FLOAT::SMALLINT,
    NULLIF(TRIM(passes_completed), '')::FLOAT::SMALLINT,
    NULLIF(TRIM(passes_attempted), '')::FLOAT::SMALLINT,
    NULLIF(TRIM(corners), '')::FLOAT::SMALLINT,
    NULLIF(TRIM(fouls), '')::FLOAT::SMALLINT,
    TRIM(team_prior_matches)::FLOAT::SMALLINT,
    TRIM(team_prior_win_rate)::NUMERIC(5,4),
    TRIM(team_prior_goals_scored_avg)::NUMERIC(5,2),
    TRIM(team_prior_goals_conceded_avg)::NUMERIC(5,2),
    TRIM(opp_prior_matches)::FLOAT::SMALLINT,
    TRIM(opp_prior_win_rate)::NUMERIC(5,4),
    TRIM(opp_prior_goals_scored_avg)::NUMERIC(5,2),
    TRIM(opp_prior_goals_conceded_avg)::NUMERIC(5,2),
    TRIM(h2h_prior_matches)::FLOAT::SMALLINT,
    TRIM(h2h_prior_win_rate)::NUMERIC(5,4),
    TRIM(team_curr_form_pts_avg)::NUMERIC(5,2),
    TRIM(team_curr_goals_scored_avg)::NUMERIC(5,2),
    TRIM(team_curr_goals_conceded_avg)::NUMERIC(5,2),
    TRIM(opp_curr_form_pts_avg)::NUMERIC(5,2),
    TRIM(opp_curr_goals_scored_avg)::NUMERIC(5,2),
    TRIM(opp_curr_goals_conceded_avg)::NUMERIC(5,2),
    NULLIF(TRIM(possession_h1), '')::NUMERIC(5,2),
    NULLIF(TRIM(possession_h2), '')::NUMERIC(5,2),
    NULLIF(TRIM(shots_h1), '')::FLOAT::SMALLINT,
    NULLIF(TRIM(shots_h2), '')::FLOAT::SMALLINT,
    NULLIF(TRIM(shots_on_target_h1), '')::FLOAT::SMALLINT,
    NULLIF(TRIM(shots_on_target_h2), '')::FLOAT::SMALLINT,
    NULLIF(TRIM(passes_completed_h1), '')::FLOAT::SMALLINT,
    NULLIF(TRIM(passes_completed_h2), '')::FLOAT::SMALLINT,
    NULLIF(TRIM(passes_attempted_h1), '')::FLOAT::SMALLINT,
    NULLIF(TRIM(passes_attempted_h2), '')::FLOAT::SMALLINT,
    NULLIF(TRIM(corners_h1), '')::FLOAT::SMALLINT,
    NULLIF(TRIM(corners_h2), '')::FLOAT::SMALLINT,
    NULLIF(TRIM(fouls_h1), '')::FLOAT::SMALLINT,
    NULLIF(TRIM(fouls_h2), '')::FLOAT::SMALLINT,
    NULLIF(TRIM(yellow_cards_h1), '')::FLOAT::SMALLINT,
    NULLIF(TRIM(yellow_cards_h2), '')::FLOAT::SMALLINT,
    NULLIF(TRIM(red_cards_h1), '')::FLOAT::SMALLINT,
    NULLIF(TRIM(red_cards_h2), '')::FLOAT::SMALLINT,
    TRIM(outcome)
FROM raw.raw_fifa_wc;